name: Build angular

on:
  push:
    branches: [ "main" ]

jobs:
  build-angular:
    runs-on: ubuntu-latest
    steps:
     -  uses: actions/checkout@v6

     - name: Setup node js
       uses: actions/setup-node@v6
       with:
         node-version: 22.x

     - name: Install dependencies
       run: npm install
      
     - name: Build
       run: npm run build

     - name: Build artifact
       uses: actions/upload-artifact@v6
       with:
         name: build dist
         path: dist
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Test job2"
        
  deploy-angular:
    runs-on: ubuntu-latest
    if: ${{always()}}
    needs:
       - build-angular
       - job2
    steps:
      - name: Deploy
        run: echo "Test step"
