name: Maual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name"
        type: string
        default: 'test'
    
jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Maual Hello, world! The runner is ready."
